sudo: required

language: generic

git:
  depth: 1

services:
  - docker

env:
  - VERSION=0.9.2
  - VERSION=0.10.0
  - NEWEST

before_install:
  - docker pull centos:7

script:
  - docker run
      --env CI=true
      --env VERSION=$VERSION
      --rm
      --volume $PWD/common:/usr/local/rpm-specs
      --volume $PWD:/usr/local/rpm-specs/package
      --workdir /usr/local/rpm-specs/package
      centos:7 ./prepare.sh
