name: ubuntu

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'
      - rrrooommmaaa-7-gha

env:
  CORES: 2
  BUILD_MODE: normal
  GPG_VERSION: stable
  PROJECT_NAME: rnp

jobs:
  rpm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: centos:7
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v1
      - name: rpm-spec
        run: |
          yum install -y git
          git clone --depth 1 https://github.com/riboseinc/rpm-specs ~/rpm-specs
      - name: Build RPM
        env:
          OUTPUT_DIR: /home/runner/work/rpmbuild
        run: ./prepare.sh
      - name: Uploading artifact
        uses: actions/upload-artifact@v1
        with:
          name: rpmbuild
          path: /home/runner/work/rpmbuild
      - name: Release
        env:
          RPM_DIR: /home/runner/work/rpmbuild
          PRIMARY_RPM: rnp*.rpm
        run: ./release.sh
